# Generated by Django 4.2.9 on 2026-03-06 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('booking_date', models.DateField()),
                ('group_size', models.PositiveIntegerField(default=1)),
                ('special_requests', models.TextField(blank=True)),
                ('tourist_name', models.CharField(max_length=200)),
                ('tourist_email', models.EmailField(max_length=254)),
                ('tourist_phone', models.CharField(max_length=20)),
                ('tourist_nationality', models.CharField(blank=True, max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('host_payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('airtel', 'Airtel Money'), ('card', 'Card'), ('pay_on_arrival', 'Pay on Arrival')], default='pay_on_arrival', max_length=20)),
                ('host_payout_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('flutterwave_tx_ref', models.CharField(blank=True, max_length=100)),
                ('flutterwave_tx_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='experiences.experience')),
                ('tourist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
