# Generated by Django 4.2.9 on 2026-03-06 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(default='🌍', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('district', models.CharField(choices=[('kabale', 'Kabale'), ('kisoro', 'Kisoro'), ('rubanda', 'Rubanda'), ('rukungiri', 'Rukungiri'), ('kanungu', 'Kanungu'), ('rukiga', 'Rukiga')], default='kabale', max_length=50)),
                ('duration_hours', models.FloatField(choices=[(1.0, '1 hour'), (1.5, '1.5 hours'), (2.0, '2 hours'), (3.0, '3 hours'), (4.0, 'Half day (4 hrs)'), (6.0, '6 hours'), (8.0, 'Full day (8 hrs)')], default=2.0)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_group_size', models.PositiveIntegerField(default=1)),
                ('max_group_size', models.PositiveIntegerField(default=15)),
                ('meeting_point', models.TextField()),
                ('whats_included', models.JSONField(blank=True, default=list)),
                ('what_to_bring', models.JSONField(blank=True, default=list)),
                ('available_days', models.JSONField(blank=True, default=list, help_text='List of days: monday, tuesday, etc.')),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='experiences.category')),
                ('host', models.ForeignKey(limit_choices_to={'role': 'host'}, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='experiences.experience')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
